spring:
  datasource:
    dynamic:
      datasource:
        base:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/base?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: root
          password: 373881
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jssaas?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: root
          password: 373881
#          druid: # 以下参数针对每个库可以重新设置druid参数
#            initial-size:
#            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
#            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter。
